apiVersion: v2
name: feedbacksystem
description: Intelligent, personalized feedback for students using artificial intelligence
icon: https://frits.mni.thm.de/img/hub/fbs-logo.png
sources:
  - https://github.com/thm-mni-ii/feedbacksystem
home: https://github.com/thm-mni-ii/feedbacksystem
type: application
version: 0.5.0
# renovate: image=thmmniii/fbs-core
appVersion: v1.4.2
dependencies:
  - name: mysql
    version: 9.4.1
    repository: 'https://charts.bitnami.com/bitnami'
    condition: core.enabled
  - name: minio
    version: 11.10.12
    repository: 'https://charts.bitnami.com/bitnami'
    condition: runner.enabled
  - name: postgresql
    version: 12.1.14
    repository: 'https://charts.bitnami.com/bitnami'
    condition: runner.enabled
    alias: runnerPostgres
  - name: mysql
    version: 9.4.1
    repository: 'https://charts.bitnami.com/bitnami'
    condition: runner.enabled
    alias: runnerMysql
  - name: mongodb
    version: 13.3.0
    repository: 'https://charts.bitnami.com/bitnami'
    condition: sqlChecker.enabled
    alias: checkerMongodb
  - name: postgresql
    version: 12.1.14
    repository: 'https://charts.bitnami.com/bitnami'
    condition: runner.enabled
    alias: runnerPlaygroundPostgres
maintainers:
  - name: zitrone44
annotations:
  artifacthub.io/license: Apache-2.0
