apiVersion: v2
name: feedbacksystem
description: Intelligent, personalized feedback for students using artificial intelligence
icon: https://frits.mni.thm.de/img/hub/fbs-logo.png
sources:
  - https://github.com/thm-mni-ii/feedbacksystem
home: https://github.com/thm-mni-ii/feedbacksystem
type: application
version: 0.47.0
# renovate: image=thmmniii/fbs-core
appVersion: v1.27.0
dependencies:
  - name: mysql
    version: 9.16.1
    repository: 'https://charts.bitnami.com/bitnami'
    condition: core.enabled
  - name: minio
    version: 12.13.1
    repository: 'https://charts.bitnami.com/bitnami'
    condition: runner.enabled
  - name: postgres
    version: 12.12.10
    repository: 'https://charts.bitnami.com/bitnami'
    condition: runner.enabled
    alias: runnerPostgres
  - name: mysql
    version: 9.16.1
    repository: 'https://charts.bitnami.com/bitnami'
    condition: runner.enabled
    alias: runnerMysql
  - name: mongodb
    version: 13.18.5
    repository: 'https://charts.bitnami.com/bitnami'
    condition: runner.sqlChecker.enabled
    alias: checkerMongodb
  - name: postgres
    version: 12.12.10
    repository: 'https://charts.bitnami.com/bitnami'
    condition: runner.enabled
    alias: runnerPlaygroundPostgres
  - name: postgres
    version: 12.12.10
    repository: 'https://charts.bitnami.com/bitnami'
    condition: runner.enabled
    alias: playgroundSharePostgres
  - name: mongodb
    version: 13.18.5
    repository: 'https://charts.bitnami.com/bitnami'
    condition: qcm.enabled
    alias: qcmMongodb
  - name: mongodb
    version: 13.18.5
    repository: 'https://charts.bitnami.com/bitnami'
    condition: runner.enabled
    alias: playgroundMongodb
maintainers:
  - name: zitrone44
annotations:
  artifacthub.io/license: Apache-2.0
