apiVersion: v2
name: feedbacksystem
description: Intelligent, personalized feedback for students using artificial intelligence
icon: https://frits.mni.thm.de/img/hub/fbs-logo.png
sources:
  - https://github.com/thm-mni-ii/feedbacksystem
home: https://github.com/thm-mni-ii/feedbacksystem
type: application
version: 0.21.0
# renovate: image=thmmniii/fbs-core
appVersion: v1.8.1
dependencies:
  - name: mysql
    version: 9.10.4
    repository: 'https://charts.bitnami.com/bitnami'
    condition: core.enabled
  - name: minio
    version: 12.6.4
    repository: 'https://charts.bitnami.com/bitnami'
    condition: runner.enabled
  - name: postgresql
    version: 12.5.8
    repository: 'https://charts.bitnami.com/bitnami'
    condition: runner.enabled
    alias: runnerPostgres
  - name: mysql
    version: 9.10.4
    repository: 'https://charts.bitnami.com/bitnami'
    condition: runner.enabled
    alias: runnerMysql
  - name: mongodb
    version: 13.15.2
    repository: 'https://charts.bitnami.com/bitnami'
    condition: runner.sqlChecker.enabled
    alias: checkerMongodb
  - name: postgresql
    version: 12.5.8
    repository: 'https://charts.bitnami.com/bitnami'
    condition: runner.enabled
    alias: runnerPlaygroundPostgres
maintainers:
  - name: zitrone44
annotations:
  artifacthub.io/license: Apache-2.0
