common:
  config:
    protocol: "https:"
    hostname: feedback.example.org
    port: 443

core:
  enabled: true
  image:
    registry: docker.io
    name: thmmniii/fbs-core
    tag: ""
    pullPolicy: "IfNotPresent"
  volumes:
    config:
      size: "8G"
      mode: "ReadWriteOnce"
    uploadDir:
      size: "16G"
      mode: "ReadWriteOnce"
  resources:
    cpu:
      request: 0.1
      limit: 2
    memory:
      request: "250Mi"
      limit: "4Gi"
  config:
    jwtSecret: "2edb8793d987389e1626918e0ec1dbee"  # CHANGE ME
    ldap:
      enabled: false
      allowLogin: false
      baseDn: ""
      url: ""
      startTls: true
      filter: "(uid={user})"
      timeout: 5000
      bind:
        enabled: false
        dn: ""
        password: ""
      attributeNames:
        uid: "uid"
        sn: "sn"
        name: "givenName"
        mail: "mail"
    digitalClassroom:  # Overwritten if digitalClassroom.enabled
      url: "https://bbb.feedback.example.org"
      secret: "1234"
    antiBruteForce:
      trustedProxyCount: 0
      interval: 600
      maxAttempts: 10
      allowList: []
    sqlPlaygroundShare:
      publicHost: "127.0.0.1"
      publicPort: 4321
    id:
      salt: "fbs-helm-chart-salt"  # Change me if you want different ids
    integrations:
      modelling:
        url: "https://fbs-modelling.mni.thm.de/"
    assa:
      url: ""
      secret: ""
    sqlRunner:
      url: ""
      insecure: false
      sharedSecret: ""
  ingressRoute:
    enabled: false

runner:
  enabled: true
  image:
    registry: docker.io
    name: thmmniii/fbs-runner
    tag: ""
    pullPolicy: "IfNotPresent"
  resources:
    cpu:
      request: 0.1
      limit: 2
    memory:
      request: "250Mi"
      limit: "4Gi"
  config:
    hmacSecret: fbs  # CHANGE ME
    debug:
      disableContainerRemoval: false
  sqlChecker:
    enabled: true
    image: "thmmniii/fbs-sql-checker:latest"
  bashChecker:
    image: "thmmniii/fbs-runtime-bash:latest"
  dink:
    image:
      registry: docker.io
      name: library/docker
      tag: "20.10.21-dind"
      pullPolicy: "IfNotPresent"
    volumes:
      images:
        size: "16G"
        mode: "ReadWriteOnce"
    resources:
      cpu:
        request: 0.1
        limit: 2
      memory:
        request: "100Mi"
        limit: "4Gi"

digitalClassroom:
  enabled: false
  image:
    registry: ghcr.io
    name: thm-mni-ii/digital-classroom
    tag: "v1.0.1"
    pullPolicy: "IfNotPresent"
  resources:
    cpu:
      request: 0.1
      limit: 2
    memory:
      request: "250Mi"
      limit: "4Gi"
  config:
    jwtSecret: "2edb8793d987389e1626918e0ec1dbee"  # CHANGE ME
    secret: "1f2a08f5dbd81580a6fb0f645dce3737"  # CHANGE ME
    path: "/digitalclassroom"
    bbb:
      url: "https://bbb.example.org"
      secret: "1234"

eat:
  enabled: false
  image:
    registry: docker.io
    name: thmmniii/fbs-eat
    tag: ""
    pullPolicy: "IfNotPresent"
  resources:
    cpu:
      request: 0.1
      limit: 2
    memory:
      request: "250Mi"
      limit: "4Gi"
  config:
    sessionSecret: fbs  # CHANGE ME
  ingressRoute:
    enabled: false

collab:
  enabled: true
  image:
    registry: docker.io
    name: thmmniii/fbs-collab
    tag: ""
    pullPolicy: "IfNotPresent"
  resources:
    cpu:
      request: 0.1
      limit: 2
    memory:
      request: "50Mi"
      limit: "1Gi"
  ingressRoute:
    enabled: false

qcm:
  enabled: true
  backend:
    image:
      registry: docker.io
      name: thmmniii/fbs-qcm-backend
      tag: ""
      pullPolicy: "IfNotPresent"
    resources:
      cpu:
        request: 0.1
        limit: 2
      memory:
        request: "50Mi"
        limit: "1Gi"
  frontend:
    image:
      registry: docker.io
      name: thmmniii/fbs-qcm-frontend
      tag: ""
      pullPolicy: "IfNotPresent"
    resources:
      cpu:
        request: 0.01
        limit: 1
      memory:
        request: "50Mi"
        limit: "1Gi"
  ingressRoute:
    enabled: false

mysql:
  image:
    repository: bitnamilegacy/mysql
  auth:
    database: fbs
    username: fbs
    password: fbs  # CHANGE ME
    rootPassword: root  # CHANGE ME
    createDatabase: true
  primary:
    existingConfigmap: '{{ .Release.Name }}-mysql-config'

runnerMysql:
  nameOverride: runner-mysql
  image:
    repository: bitnamilegacy/mysql
  auth:
    database: fbs
    username: fbs
    password: fbs  # CHANGE ME
    rootPassword: root  # CHANGE ME
  primary:
    existingConfigmap: '{{ .Release.Name }}-mysql-config'

runnerPostgres:
  nameOverride: runner-postgres
  image:
    repository: bitnamilegacy/postgresql
  auth:
    database: fbs
    username: fbs
    password: fbs  # CHANGE ME
    postgresPassword: root  # CHANGE ME

runnerPlaygroundPostgres:
  nameOverride: runner-playground-postgres
  image:
    repository: bitnamilegacy/postgresql
  auth:
    database: fbs
    username: fbs
    password: fbs  # CHANGE ME
    postgresPassword: root  # CHANGE ME

playgroundSharePostgres:
  nameOverride: playground-share-postgres
  image:
    repository: bitnamilegacy/postgresql
  auth:
    database: fbs
    username: fbs
    password: fbs  # CHANGE ME
    postgresPassword: root  # CHANGE ME

checkerMongodb:
  nameOverride: checker-mongodb
  image:
    repository: bitnamilegacy/mongodb
  useStatefulSet: true
  auth:
    database: fbs
    username: fbs
    password: fbs  # CHANGE ME
    rootPassword: root  # CHANGE ME

qcmMongodb:
  nameOverride: qcm-mongodb
  image:
    repository: bitnamilegacy/mongodb
  useStatefulSet: true
  auth:
    database: fbs
    username: fbs
    password: fbs  # CHANGE ME
    rootPassword: root  # CHANGE ME

playgroundMongodb:
  nameOverride: mongodb-playground
  image:
    repository: bitnamilegacy/mongodb
  useStatefulSet: true
  auth:
    database: playground-db
    username: fbs
    password: fbs  # CHANGE ME
    rootPassword: root  # CHANGE ME

parsr:
  enabled: false
  image:
    registry: docker.io
    name: axarev/parsr
    tag: "latest"
    pullPolicy: "IfNotPresent"
  resources:
    cpu:
      request: 0.1
      limit: 2
    memory:
      request: "250Mi"
      limit: "4Gi"
  volumes:
    output:
      size: "8G"
      mode: "ReadWriteOnce"

minio:
  auth:
    rootPassword: fbs-12345678  # CHANGE ME
