common:
  config:
    protocol: "https:"
    hostname: feedback.example.org
    port: 443

webShell:
  enabled: true
  image:
    registry: ghcr.io
    name: thm-mni-ii/fbs-web-shell
    tag: ""
    pullPolicy: "IfNotPresent"
  resources:
    cpu:
      request: 0.01
      limit: 1
    memory:
      request: "50Mi"
      limit: "500Mi"
  ingress:
    enabled: false
    className: ""
    annotations: {}
    hosts: []
    #   - host: feedback.example.org
    #     paths:
    #       - path: /
    #         pathType: Prefix
    tls: []
    #   - secretName: feedback-tls
    #     hosts:
    #       - feedback.example.org
  ingressRoute:
    enabled: false

identity:
  enabled: true
  image:
    registry: ghcr.io
    name: thm-mni-ii/fbs-identity-service
    tag: ""
    pullPolicy: "IfNotPresent"
  resources:
    cpu:
      request: 0.1
      limit: 2
    memory:
      request: "250Mi"
      limit: "4Gi"
  config:
    saml:
      enabled: false
      registrationId: "keycloak"  # e.g. "thm" or "keycloak"
      idpMetadataUri: ""  # e.g. "https://idp.thm.de/idp/shibboleth"
      idpEntityId: ""
      idpSsoUrl: ""
      spEntityId: ""  # Defaults to https://<host>/saml2/metadata/<registrationId> if empty
      principalAttribute: "uid"
      prenameAttribute: "givenName"
      surnameAttribute: "sn"
      emailAttribute: "mail"
      signRequest: false
    oidc:
      issuer: ""  # Overwritten with common host if empty
      jwkSetUri: ""  # Overwritten with internal identity service endpoint if empty
      clientId: "fbs-web-shell,fbs-test-client"
      redirectUris: []
      postLogoutRedirectUris: []
      accessTokenTtlMinutes: 15
      authCodeTtlMinutes: 5
    signingKey:
      existingSecret: ""  # Name of existing secret containing identity-signing-key.p12
      secretKey: "identity-signing-key.p12"
      keystore: ""  # Base64 encoded .p12 keystore file if not using existingSecret
      storePassword: "changeit"  # CHANGE ME
      alias: "identity-signing"
      keyPassword: "changeit"  # CHANGE ME
    antiBruteForce:
      maxFailuresPerIp: 150
      maxFailuresPerIpUser: 15
      windowSeconds: 600
      trustedProxies: 0
      allowList: []
  ingress:
    enabled: false
    className: ""
    annotations: {}
    hosts: []
    #   - host: feedback.example.org
    #     paths:
    #       - path: /oauth2
    #         pathType: Prefix
    tls: []
    #   - secretName: feedback-tls
    #     hosts:
    #       - feedback.example.org
  ingressRoute:
    enabled: false

courseManagementWeb:
  enabled: true
  image:
    registry: ghcr.io
    name: thm-mni-ii/fbs-core-web
    tag: ""
    pullPolicy: "IfNotPresent"
  resources:
    cpu:
      request: 0.01
      limit: 1
    memory:
      request: "50Mi"
      limit: "500Mi"
  ingress:
    enabled: false
    className: ""
    annotations: {}
    pathPrefix: "/course-management"
    hosts: []
    #   - host: feedback.example.org
    #     paths:
    #       - path: /course-management
    #         pathType: Prefix
    tls: []
    #   - secretName: feedback-tls
    #     hosts:
    #       - feedback.example.org
  ingressRoute:
    enabled: false
    pathPrefix: "/course-management"

sqlPlaygroundWeb:
  enabled: true
  image:
    registry: ghcr.io
    name: thm-mni-ii/fbs-sql-playground-web
    tag: ""
    pullPolicy: "IfNotPresent"
  resources:
    cpu:
      request: 0.01
      limit: 1
    memory:
      request: "50Mi"
      limit: "500Mi"
  ingress:
    enabled: false
    className: ""
    annotations: {}
    pathPrefix: "/sql-playground"
    hosts: []
    #   - host: feedback.example.org
    #     paths:
    #       - path: /sql-playground
    #         pathType: Prefix
    tls: []
    #   - secretName: feedback-tls
    #     hosts:
    #       - feedback.example.org
  ingressRoute:
    enabled: false
    pathPrefix: "/sql-playground"

core:
  enabled: true
  image:
    registry: ghcr.io
    name: thm-mni-ii/fbs-core
    tag: ""
    pullPolicy: "IfNotPresent"
  volumes:
    config:
      size: "8G"
      mode: "ReadWriteOnce"
    uploadDir:
      size: "16G"
      mode: "ReadWriteOnce"
  resources:
    cpu:
      request: 0.1
      limit: 2
    memory:
      request: "250Mi"
      limit: "4Gi"
  probes:
    readiness:
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3
    liveness:
      initialDelaySeconds: 60
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 6
  config:
    jwtSecret: "2edb8793d987389e1626918e0ec1dbee"  # CHANGE ME
    ldap:
      enabled: false
      allowLogin: false
      baseDn: ""
      url: ""
      startTls: true
      filter: "(uid={user})"
      timeout: 5000
      bind:
        enabled: false
        dn: ""
        password: ""
      attributeNames:
        uid: "uid"
        sn: "sn"
        name: "givenName"
        mail: "mail"
    digitalClassroom:  # Overwritten if digitalClassroom.enabled
      url: "https://bbb.feedback.example.org"
      secret: "1234"
    antiBruteForce:
      trustedProxyCount: 0
      interval: 600
      maxAttempts: 10
      allowList: []
    sqlPlaygroundShare:
      publicHost: "127.0.0.1"
      publicPort: 4321
    id:
      salt: "fbs-helm-chart-salt"  # Change me if you want different ids
    integrations:
      modelling:
        url: "https://fbs-modelling.mni.thm.de/"
    assa:
      url: ""
      secret: ""
    sqlRunner:
      url: ""
      insecure: false
      sharedSecret: ""
  ingress:
    enabled: false
    className: ""
    annotations: {}
    servicePort: 443
    hosts: []
    #   - host: feedback.example.org
    #     paths:
    #       - path: /api/v1
    #         pathType: Prefix
    #       - path: /results
    #         pathType: Prefix
    tls: []
    #   - secretName: feedback-tls
    #     hosts:
    #       - feedback.example.org
  ingressRoute:
    enabled: false

runner:
  enabled: true
  image:
    registry: ghcr.io
    name: thm-mni-ii/fbs-runner
    tag: ""
    pullPolicy: "IfNotPresent"
  resources:
    cpu:
      request: 0.1
      limit: 2
    memory:
      request: "250Mi"
      limit: "4Gi"
  config:
    hmacSecret: fbs  # CHANGE ME
    debug:
      disableContainerRemoval: false
  sqlChecker:
    enabled: true
    image: "ghcr.io/thm-mni-ii/fbs-sql-checker:latest"
  bashChecker:
    image: "ghcr.io/thm-mni-ii/fbs-runtime-bash:latest"
  dink:
    image:
      registry: docker.io
      name: library/docker
      tag: "20.10.21-dind"
      pullPolicy: "IfNotPresent"
    volumes:
      images:
        size: "16G"
        mode: "ReadWriteOnce"
    resources:
      cpu:
        request: 0.1
        limit: 2
      memory:
        request: "100Mi"
        limit: "4Gi"

digitalClassroom:
  enabled: false
  image:
    registry: ghcr.io
    name: thm-mni-ii/digital-classroom
    tag: "v1.0.1"
    pullPolicy: "IfNotPresent"
  resources:
    cpu:
      request: 0.1
      limit: 2
    memory:
      request: "250Mi"
      limit: "4Gi"
  config:
    jwtSecret: "2edb8793d987389e1626918e0ec1dbee"  # CHANGE ME
    secret: "1f2a08f5dbd81580a6fb0f645dce3737"  # CHANGE ME
    path: "/digitalclassroom"
    bbb:
      url: "https://bbb.example.org"
      secret: "1234"

eat:
  enabled: false
  image:
    registry: ghcr.io
    name: thm-mni-ii/fbs-eat
    tag: ""
    pullPolicy: "IfNotPresent"
  resources:
    cpu:
      request: 0.1
      limit: 2
    memory:
      request: "250Mi"
      limit: "4Gi"
  config:
    sessionSecret: fbs  # CHANGE ME
  ingress:
    enabled: false
    className: ""
    annotations: {}
    hosts: []
    #   - host: feedback.example.org
    #     paths:
    #       - path: /eat
    #         pathType: Prefix
    tls: []
    #   - secretName: feedback-tls
    #     hosts:
    #       - feedback.example.org
  ingressRoute:
    enabled: false

collab:
  enabled: true
  image:
    registry: ghcr.io
    name: thm-mni-ii/fbs-collab
    tag: ""
    pullPolicy: "IfNotPresent"
  resources:
    cpu:
      request: 0.1
      limit: 2
    memory:
      request: "50Mi"
      limit: "1Gi"
  ingress:
    enabled: false
    className: ""
    annotations: {}
    hosts: []
    #   - host: feedback.example.org
    #     paths:
    #       - path: /collab
    #         pathType: Prefix
    tls: []
    #   - secretName: feedback-tls
    #     hosts:
    #       - feedback.example.org
  ingressRoute:
    enabled: false

qcm:
  enabled: true
  backend:
    image:
      registry: ghcr.io
      name: thm-mni-ii/fbs-qcm-backend
      tag: ""
      pullPolicy: "IfNotPresent"
    resources:
      cpu:
        request: 0.1
        limit: 2
      memory:
        request: "50Mi"
        limit: "1Gi"
  frontend:
    image:
      registry: ghcr.io
      name: thm-mni-ii/fbs-qcm-frontend
      tag: ""
      pullPolicy: "IfNotPresent"
    resources:
      cpu:
        request: 0.01
        limit: 1
      memory:
        request: "50Mi"
        limit: "1Gi"
    config:
      backendUrl: ""
      coreUrl: ""
  ingress:
    enabled: false
    className: ""
    annotations: {}
    hosts: []
    #   - host: feedback.example.org
    #     paths:
    #       - path: /questionary
    #         pathType: Prefix
    #       - path: /questionary/api_v1
    #         pathType: Prefix
    tls: []
    #   - secretName: feedback-tls
    #     hosts:
    #       - feedback.example.org
  ingressRoute:
    enabled: false

mysql:
  image:
    repository: bitnamilegacy/mysql
  auth:
    database: fbs
    username: fbs
    password: fbs  # CHANGE ME
    rootPassword: root  # CHANGE ME
    createDatabase: true
  initdbScriptsConfigMap: '{{ .Release.Name }}-mysql-init-scripts'
  primary:
    existingConfigmap: '{{ .Release.Name }}-mysql-config'

runnerMysql:
  nameOverride: runner-mysql
  image:
    repository: bitnamilegacy/mysql
  auth:
    database: fbs
    username: fbs
    password: fbs  # CHANGE ME
    rootPassword: root  # CHANGE ME
  primary:
    existingConfigmap: '{{ .Release.Name }}-mysql-config'

runnerPostgres:
  nameOverride: runner-postgres
  image:
    repository: bitnamilegacy/postgresql
  auth:
    database: fbs
    username: fbs
    password: fbs  # CHANGE ME
    postgresPassword: root  # CHANGE ME

runnerPlaygroundPostgres:
  nameOverride: runner-playground-postgres
  image:
    repository: bitnamilegacy/postgresql
  auth:
    database: fbs
    username: fbs
    password: fbs  # CHANGE ME
    postgresPassword: root  # CHANGE ME

playgroundSharePostgres:
  nameOverride: playground-share-postgres
  image:
    repository: bitnamilegacy/postgresql
  auth:
    database: fbs
    username: fbs
    password: fbs  # CHANGE ME
    postgresPassword: root  # CHANGE ME

checkerMongodb:
  nameOverride: checker-mongodb
  image:
    repository: bitnamilegacy/mongodb
  useStatefulSet: true
  auth:
    database: fbs
    username: fbs
    password: fbs  # CHANGE ME
    rootPassword: root  # CHANGE ME

qcmMongodb:
  nameOverride: qcm-mongodb
  image:
    repository: bitnamilegacy/mongodb
  useStatefulSet: true
  auth:
    database: fbs
    username: fbs
    password: fbs  # CHANGE ME
    rootPassword: root  # CHANGE ME

playgroundMongodb:
  nameOverride: mongodb-playground
  image:
    repository: bitnamilegacy/mongodb
  useStatefulSet: true
  auth:
    database: playground-db
    username: fbs
    password: fbs  # CHANGE ME
    rootPassword: root  # CHANGE ME

parsr:
  enabled: false
  image:
    registry: docker.io
    name: axarev/parsr
    tag: "latest"
    pullPolicy: "IfNotPresent"
  resources:
    cpu:
      request: 0.1
      limit: 2
    memory:
      request: "250Mi"
      limit: "4Gi"
  volumes:
    output:
      size: "8G"
      mode: "ReadWriteOnce"

minio:
  image:
    repository: bitnamilegacy/minio
  auth:
    rootPassword: fbs-12345678  # CHANGE ME
