common:
  config:
    protocol: "https:"
    hostname: feedback.example.org
    port: 443

core:
  enabled: true
  image:
    registry: docker.io
    name: thmmniii/fbs-core
    tag: ""
    pullPolicy: "IfNotPresent"
  volumes:
    config:
      size: "8G"
      mode: "ReadWriteOnce"
    uploadDir:
      size: "16G"
      mode: "ReadWriteOnce"
  resources:
    cpu:
      request: 0.1
      limit: 2
    memory:
      request: "250Mi"
      limit: "4Gi"
  config:
    jwtSecret: "2edb8793d987389e1626918e0ec1dbee"  # CHANGE ME
    ldap:
      enabled: false
      allowLogin: false
      baseDn: ""
      url: ""
      startTls: true
      filter: "(uid={user})"
      timeout: 5000
      bind:
        enabled: false
        dn: ""
        password: ""
      attributeNames:
        uid: "uid"
        sn: "sn"
        name: "givenName"
        mail: "mail"
    digitalClassroom: # Overwritten if digitalClassroom.enabled
      url: "https://bbb.feedback.example.org"
      secret: "1234"
  ingress:
    enabled: true

runner:
  enabled: true
  image:
    registry: docker.io
    name: thmmniii/fbs-runner
    tag: ""
    pullPolicy: "IfNotPresent"
  resources:
    cpu:
      request: 0.1
      limit: 2
    memory:
      request: "250Mi"
      limit: "4Gi"
  config:
    hmacSecret: fbs  # CHANGE ME
    debug:
      disableContainerRemoval: false
  sqlChecker:
    enabled: true
    image: "thmmniii/fbs-sql-checker:latest"
  bashChecker:
    image: "thmmniii/fbs-runtime-bash:latest"
  dink:
    image:
      registry: docker.io
      name: library/docker
      tag: "20.10.21-dind"
      pullPolicy: "IfNotPresent"
    volumes:
      images:
        size: "16G"
        mode: "ReadWriteOnce"
    resources:
      cpu:
        request: 0.1
        limit: 2
      memory:
        request: "100Mi"
        limit: "4Gi"

digitalClassroom:
  enabled: false
  image:
    registry: ghcr.io
    name: thm-mni-ii/digital-classroom
    tag: "v1.0.1"
    pullPolicy: "IfNotPresent"
  resources:
    cpu:
      request: 0.1
      limit: 2
    memory:
      request: "250Mi"
      limit: "4Gi"
  config:
    jwtSecret: "2edb8793d987389e1626918e0ec1dbee"  # CHANGE ME
    secret: "1f2a08f5dbd81580a6fb0f645dce3737"  # CHANGE ME
    path: "/digitalclassroom"
    bbb:
      url: "https://bbb.example.org"
      secret: "1234"

mysql:
  auth:
    database: fbs
    username: fbs
    password: fbs  # CHANGE ME
    rootPassword: root  # CHANGE ME
    createDatabase: true
  primary:
    existingConfigmap: 'CHANGE-ME'

runnerMysql:
  nameOverride: runner-mysql
  auth:
    database: fbs
    username: fbs
    password: fbs  # CHANGE ME
    rootPassword: root  # CHANGE ME
  primary:
    existingConfigmap: 'CHANGE-ME'

runnerPostgres:
  nameOverride: runner-postgres
  auth:
    database: fbs
    username: fbs
    password: fbs  # CHANGE ME
    postgresPassword: root  # CHANGE ME

runnerPlaygroundPostgres:
  nameOverride: runner-playground-postgres
  auth:
    database: fbs
    username: fbs
    password: fbs  # CHANGE ME
    postgresPassword: root  # CHANGE ME

checkerMongodb:
  nameOverride: checker-mongodb
  auth:
    database: fbs
    username: fbs
    password: fbs  # CHANGE ME
    rootPassword: root  # CHANGE ME

minio:
  auth:
    rootPassword: fbs-12345678  # CHANGE ME
